/*
 * generated by Xtext
 */
package org.eclipse.xtext.xdoc.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XdocProposalProvider extends AbstractXdocProposalProvider {
}
