/*
 * generated by Xtext
 */
package org.eclipse.xtext.xdoc.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class XdocUiModule extends AbstractXdocUiModule {
}
