/*
 * generated by Xtext
 */
package org.eclipse.xtext.xdoc.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class XdocScopeProvider extends AbstractXdocScopeProvider {

}
