/**
 * generated by Xtext
 */
package org.eclipse.xtext.xdoc.ide;

import org.eclipse.xtext.xdoc.ide.AbstractXdocIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XdocIdeModule extends AbstractXdocIdeModule {
}
