/**
 * generated by Xtext
 */
package org.eclipse.xtext.xdoc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.eclipse.xtext.xdoc.XdocRuntimeModule;
import org.eclipse.xtext.xdoc.XdocStandaloneSetup;
import org.eclipse.xtext.xdoc.ide.XdocIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class XdocIdeSetup extends XdocStandaloneSetup {
  @Override
  public Injector createInjector() {
    XdocRuntimeModule _xdocRuntimeModule = new XdocRuntimeModule();
    XdocIdeModule _xdocIdeModule = new XdocIdeModule();
    return Guice.createInjector(Modules2.mixin(_xdocRuntimeModule, _xdocIdeModule));
  }
}
