/*
 * generated by Xtext
 */
package org.eclipse.xtext.xdoc.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.eclipse.xtext.xdoc.ui.internal.XdocActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XdocExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XdocActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XdocActivator.getInstance().getInjector(XdocActivator.ORG_ECLIPSE_XTEXT_XDOC_XDOC);
	}
	
}
